name: deployment pipeline

on:
  push:
    branches:
      - master

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: pokemoncicd
          heroku_email: anpesip99@gmail.com
          healthcheck: https://pokemoncicd.herokuapp.com/health
          checkstring: ok
          rollbackonhealthcheckfailed: true
